/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#FF5733",
          "primary-content": "#FFFFFF",
          secondary: "#FF9047",
          "secondary-content": "#FFFFFF",
          accent: "#D14124",
          "accent-content": "#FFFFFF",
          neutral: "#2A2A2A",
          "neutral-content": "#FFFFFF",
          "base-100": "#FFF5F1",
          "base-200": "#FFE8E0",
          "base-300": "#FFCCBF",
          "base-content": "#382218",
          info: "#3ABFF8",
          success: "#36D399",
          warning: "#FBBD23",
          error: "#F87272",
          "--rounded-btn": "1.5rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#FF5733",
          "primary-content": "#FFFFFF",
          secondary: "#FF9047",
          "secondary-content": "#FFFFFF",
          accent: "#D14124",
          "accent-content": "#FFFFFF",
          neutral: "#FFE8E0",
          "neutral-content": "#382218",
          "base-100": "#2A2A2A",
          "base-200": "#222222",
          "base-300": "#1A1A1A",
          "base-content": "#FFF5F1",
          info: "#3ABFF8",
          success: "#36D399",
          warning: "#FBBD23",
          error: "#F87272",
          "--rounded-btn": "1.5rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      fontFamily: { "space-grotesk": ["Space Grotesk", "sans-serif"] },
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
    },
  },
};
